[package]
name = "hs-probe-bsp"
version = "0.1.0"
authors = ["Vadim Kaushan <admin@disasm.info>"]
edition = "2018"

[dependencies]
cortex-m = "0.6.2"
stm32ral = { version = "0.4.1", features = ["stm32f7x3"] }
synopsys-usb-otg = { version = "0.2.0", features = ["cortex-m", "fs"] }
num_enum = { version = "0.4.3", default-features = false }